AI Programming - SW Lee

# Lab 01: Numpy Basic

In [ ]:
import numpy as np  # import the package "numpy"

# set the option values 
depth = 3
np_row = 3
np_column = 3
output_num = 8

np.random.seed(622) # seed value is 622

### START CODE HERE ###
# random seed [0,1)
rand_array1 = np.random.rand(depth,np_row,np_column) # get rand array [0,1) (3, 3, 3) 
rand_array2 = np.random.rand(output_num,depth,np_row,np_column) # get rand array [0,1) (8, 3, 3, 3) 

output1 = rand_array1 * rand_array2 # calculate rand_array1 * rand_array2 with broadcast 
output2 = output1.reshape(-1, np_row*np_column) # reshape the output1 shape ( ,np_row*np_column) 

max_index = np.argmax(output2, axis=-1) # get max_index (axis = -1)
max_num = np.max(output2, axis=-1) # get max_num (axis = -1)

one_hot = np.eye(output_num+1)[max_index]# Get the one_hot array form rand_array with max_index

 ###  END CODE HERE  ###

In [ ]:
print(f"shape of rand_array1 = {rand_array1.shape} \n rand_array1[0,...] = \n{rand_array1[0,...]}\n")
print(f"shape of rand_array2 = {rand_array2.shape} \n rand_array2[2,0,...] = \n{rand_array2[2,0,...]}\n")
print(f"output1[2,0,...] = \n{output1[2,0,...]}\n")
print(f"max_index : {max_index[3:6]}\n")
print(f"max_num : {max_num[3:6]}\n")
print(f"one_hot: {one_hot[3:5]}")

shape of rand_array1 = (3, 3, 3) 
 rand_array1[0,...] = 
[[0.66065661 0.87143953 0.19708822]
 [0.28077271 0.51250531 0.49405338]
 [0.22509396 0.14382491 0.17562611]]

shape of rand_array2 = (8, 3, 3, 3) 
 rand_array2[2,0,...] = 
[[0.43525402 0.39112109 0.68430252]
 [0.60701687 0.65487832 0.90284221]
 [0.68154913 0.93094495 0.62065594]]

output1[2,0,...] = 
[[0.28755344 0.34083838 0.13486797]
 [0.17043377 0.33562862 0.44605225]
 [0.15341259 0.13389308 0.10900339]]

max_index : [0 5 3]

max_num : [0.45075217 0.44127979 0.39931943]

one_hot: [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]
